### ISSUE TITLE
背中の曲がった男がID124までしかトリプル化されていない

### ISSUE THREAD

**Issue by Ease112** [KnowledgeGraphJapan/KGRC-RDF#1]
背中の曲がった男がID124までしかトリプル化されていない

**Comment by koujikozaki** [comment]
・原因１
場面151のhasPredicate	「いた」の英語が「空白」だった
・原因２
場面317の「1857-07-09」という記載が，「別場面への参照（※）」として判定されエラーが出ていた．
→「1857年07月09日」とすることで回避
（※） "[0-9,-]*";という正規表現で判定している

**Comment by koujikozaki** [comment]
前述の修正をしたうえで，RDFを作成しなおしたものに更新．
