### ISSUE TITLE
一部のActivityがvh2kg_schema.ttlと対応づいていない

### ISSUE THREAD

**Issue by s246wv** [KnowledgeGraphJapan/KGRC-RDF#30]
[kgrc4si](https://github.com/KnowledgeGraphJapan/KGRC-RDF/tree/kgrc4si)ブランチについてです．

Activityを表すttlファイルの一部で`:Event`のインスタンスを持つ(`:hasEvent`)インスタンスが，`ho:Activity`の下位クラスのインスタンスとしては与えられていないようです．

具体的には，
virtualhome2kg-Eat_Bread.ttl
virtualhome2kg-Prepare_Go_Out.ttl
virtualhome2kg-Put_food_in_Fridge.ttl
virtualhome2kg-Throw_in_garbage.ttl
virtualhome2kg-Wash_Fry_Pan.ttl
virtualhome2kg-leaving_room.ttl
virtualhome2kg-Cook_Food.ttl
の中の，
`ho:eat_bread`
`ho:prepare_go_out`
`ho:put_food_in_fridge`
`ho:throw_in_the_garbage`
`ho:wash_fry_pan`
`ho:leaving_room`
`ho:cook_food`
が，vh2kg_schema.ttlにありませんでした．

```sparql
prefix ho: <http://www.owl-ontologies.com/VirtualHome.owl#> 
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
select * where { 
    ?s a ?o.
    ?o rdfs:subClassOf+ ho:Activity .
} order by ?o
```
このようなクエリでActivityのインスタンス一覧を取得しようとすると上記の7つのActivityに関しては取得することができませんでした．

**Comment by Ease112** [comment]
@s246wv 様
ご指摘いただきありがとうございます。
上記の件についてvh2kg_schema.ttlを修正いたしました。
よろしくお願いいたします。
