### ISSUE TITLE
先日のアップデートにより僧坊荘園 (AbbeyGrange) が大きく乱れている

### ISSUE THREAD

**Issue by RyoyaKaneda-Student** [KnowledgeGraphJapan/KGRC-RDF#33]
2022年11月5日にデータを少し更新された際,  僧坊荘園（AbbeyGrange.ttl）の作品において大きく乱れましたのでご報告いたしました. 
特に, ファイル上のストーリーの020付近にありますオブジェクト
\< http://kgc.knowledge-graph.jp/data/AbbeyGrange/・Opposite >
や, 042付近にあるオブジェクト
\< http://kgc.knowledge-graph.jp/data/AbbeyGrange/・otherwise（さもないと） >
などは明らかに誤りかと思われます. それらを含めまして誤りなのかわからないタグが多く見られました. 
お手数ですが直していただけると幸いです. 

また, こちらの小説を含めまして, 同じストーリーNoに対して複数のTypeが付与されているデータが各小説内にいくつか見られます. 
このような No は複数のタイプ属性を持つストーリー, として解釈すればよろしいのでしょうか.

**Comment by koujikozaki** [comment]
ご連絡ありがとうございます．
その後，さらにデータの更新を行ったのですが，ご指摘のありました「僧坊荘園（AbbeyGrange.ttl）についての乱れ」は解消できておりませんでした．

原因を調査の上，再度，修正したものをアップするようにいたしますので，しばらくお待ちください．

>  また, こちらの小説を含めまして, 同じストーリーNoに対して複数のTypeが付与されているデータが各小説内にいくつか見られます.
> このような No は複数のタイプ属性を持つストーリー, として解釈すればよろしいのでしょうか.

のように，同一のストーリーNoに対して複数のTypeを付与することは想定しおりません．
よって，僧坊荘園（AbbeyGrange.ttl）についてはデータ作成時のエラーとなります．

**Comment by koujikozaki** [comment]
https://github.com/KnowledgeGraphJapan/KGRC-RDF/pull/35
で対応が完了しました．
