### ISSUE TITLE
Adding the ontology into LOV

### ISSUE THREAD

**Issue by gatemezing** [KnowledgeGraphJapan/KGRC-RDF#39]
Hello,
I just discovered this nice KG during a presentation at ESWC2023 in Greece. I wanted to add the ontology into the [LOV catalog](https://lov.linkeddata.es/dataset/lov/), but it seems that there are issues with content negotiation. 
For e.g., 
```
curl -I -L http://kgc.knowledge-graph.jp/ontology/kgc.owl
HTTP/1.1 200 OK
Date: Mon, 29 May 2023 11:58:25 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Server: Apache
X-Powered-By: PHP/7.4.30
Vary: Range
Accept-Ranges: none

```
It seems that the server retrieve text/html instead of RDF serialization. Could you fix that to be [suggested in LOV](https://lov.linkeddata.es/dataset/lov/suggest)?

**Comment by Ease112** [comment]
@gatemezing 
I appreciate your interest!
It is a very nice suggestion!
We will attempt to change the settings soon.

**Comment by Ease112** [comment]
@gatemezing 
I have modified the server's content negotiation settings and suggested our owl file to LOV. Thank you for your advice.
